FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml ./
COPY ./requirements.txt ./
COPY ./src/ /app/

RUN pip install --upgrade pip && pip install -r requirements.txt && pip install "mcp[cli]"

EXPOSE 6274

CMD ["sh", "-c", "pip show mcp && python -m mcp_kipris.sse_server --http --host 0.0.0.0 --port 6274"]
