FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml ./
COPY ./requirements.txt ./
COPY ./src/ /app/

RUN pip install --upgrade pip && pip install -r requirements.txt && pip install "mcp[cli]" uvicorn starlette

EXPOSE 6274

CMD ["sh", "-c", "python /streamable_server.py"]
