FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml ./
COPY ./requirements.txt ./
COPY ./src/ /app/

RUN pip install --upgrade pip && pip install -r requirements.txt && pip install "mcp[cli]"

EXPOSE 6274

CMD ["sh", "-c", "pip install 'mcp[cli]' && python -m mcp_kipris.streamable_server"]
